// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_sSQomYSUz7a5ukuOshE513XHqeIQek',
    appId: '1:559088204120:web:39017a886a0580adc60d2d',
    messagingSenderId: '559088204120',
    projectId: 'ia2-flutter',
    authDomain: 'ia2-flutter.firebaseapp.com',
    storageBucket: 'ia2-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3IWHM0RrRRjMsiL97yNYiwe0I1uEegc',
    appId: '1:559088204120:android:c4ca5d89a683d4abc60d2d',
    messagingSenderId: '559088204120',
    projectId: 'ia2-flutter',
    storageBucket: 'ia2-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd0uszDOpSFv9JMwfgH18nLi1t85w68vs',
    appId: '1:559088204120:ios:525d2bf069afa4fbc60d2d',
    messagingSenderId: '559088204120',
    projectId: 'ia2-flutter',
    storageBucket: 'ia2-flutter.appspot.com',
    iosBundleId: 'com.emsi.project',
  );
}
